// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -srcdir . -godefs -import_runtime_cgo=false -import_syscall=false /Users/zchee/go/src/go-darwin.dev/exp/sys/defs_darwin_amd64.go

package sys

type (
	c_short		int16
	c_int		int32
	c_int8		int8
	c_int16		int16
	c_int32		int32
	c_int64		int64
	c_long		int64
	c_longLong	int64
	c_uint		uint32
	c_uint8		uint8
	c_uint16	uint16
	c_uint32	uint32
	c_uint64	uint64
	c_char		int8
	c_float		float32
	c_double	float64
)

type kernReturn int32

const (
	kernSuccess			kernReturn	= 0x0
	kernInvalidAddress		kernReturn	= 0x1
	kernProtectionFailure		kernReturn	= 0x2
	kernNoSpace			kernReturn	= 0x3
	kernInvalidArgument		kernReturn	= 0x4
	kernFailure			kernReturn	= 0x5
	kernResourceShortage		kernReturn	= 0x6
	kernNotReceiver			kernReturn	= 0x7
	kernNoAccess			kernReturn	= 0x8
	kernMemoryFailure		kernReturn	= 0x9
	KernMemoryError			kernReturn	= 0xa
	kernAlreadyInSet		kernReturn	= 0xb
	kernNotInSet			kernReturn	= 0xc
	kernNameExists			kernReturn	= 0xd
	kernAborted			kernReturn	= 0xe
	kernInvalidName			kernReturn	= 0xf
	kernInvalidTask			kernReturn	= 0x10
	kernInvalidRight		kernReturn	= 0x11
	kernInvalidValue		kernReturn	= 0x12
	kernUrefsOverflow		kernReturn	= 0x13
	kernInvalidCapability		kernReturn	= 0x14
	kernRightExists			kernReturn	= 0x15
	kernInvalidHost			kernReturn	= 0x16
	kernMemoryPresent		kernReturn	= 0x17
	kernMemoryDataMoved		kernReturn	= 0x18
	kernMemoryRestartCopy		kernReturn	= 0x19
	kernInvalidProcessorSet		kernReturn	= 0x1a
	kernPolicyLimit			kernReturn	= 0x1b
	kernInvalidPolicy		kernReturn	= 0x1c
	kernInvalidObject		kernReturn	= 0x1d
	kernAlreadyWaiting		kernReturn	= 0x1e
	kernDefaultSet			kernReturn	= 0x1f
	kernExceptionProtected		kernReturn	= 0x20
	kernInvalidLedger		kernReturn	= 0x21
	kernInvalidMemoryControl	kernReturn	= 0x22
	kernInvalidSecurity		kernReturn	= 0x23
	kernNotDepressed		kernReturn	= 0x24
	kernTerminated			kernReturn	= 0x25
	kernLockSetDestroyed		kernReturn	= 0x26
	kernLockUnstable		kernReturn	= 0x27
	kernLockOwned			kernReturn	= 0x28
	kernLockOwnedSelf		kernReturn	= 0x29
	kernSemaphoreDestroyed		kernReturn	= 0x2a
	kernRPCServerTerminated		kernReturn	= 0x2b
	kernRPCTerminateOrphan		kernReturn	= 0x2c
	kernRPCContinueOrphan		kernReturn	= 0x2d
	kernNotSupported		kernReturn	= 0x2e
	kernNodeDown			kernReturn	= 0x2f
	kernNotWaiting			kernReturn	= 0x30
	kernOperationTimedOut		kernReturn	= 0x31
	kernCodesignError		kernReturn	= 0x32
	kernPolicyStatic		kernReturn	= 0x33
	kernInsufficientBufferSize	kernReturn	= 0x34
	kernDenied			kernReturn	= 0x35
	kernMissingKC			kernReturn	= 0x36
	kernInvalidKC			kernReturn	= 0x37
	kernReturnMax			kernReturn	= 0x100
)
