// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -srcdir . -godefs -import_runtime_cgo=false -import_syscall=false /Users/zchee/go/src/go-darwin.dev/exp/libproc/defs_darwin_amd64.go

package libproc

const (
	ProcPidpathinfoMaxsize	= 0x1000
	ProcPidpathinfoSize	= 0x400
)

type PID int32
